### ISSUE TITLE
Should we create something akin to the MODULE macros ptracer.h

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene-tracer#2]
It sounds like that part is repetitive boilerplate. If it's always the same, maybe we can create those macros ourselves?

**Comment by singul4ri7y** [comment]
I think not.

Because it is very broad and hard to say how will the modules adopt `pallene-tracer`. Some modules may use the Dispatch system like Pallene (dispatching the Lua C call to an actual C function), or some module may use the non-dispatching method. Some modules may also use static line numbers and module/filenames just like we are doing in Pallene.

Also on top of that, we need `pt_cont_t *` and the finalizer object to be passed around the function willing to be in the traceback. Now, different modules may handle it differently as well, there is no way of knowing how they would.

So finding out and including a generalized predefined macros in Pallene Tracer and keeping all the module happy would be a really hard task. I would suggest we do the ground work and let the module hackers take it from here.

**But** after the adoption of Pallene Tracer in broader modules if any repetitive pattern of the macros emerges, we may include it in the `ptracer.h`.

We can close the issue for now.

**Comment by hugomg** [comment]
>  But after the adoption of Pallene Tracer in broader modules if any repetitive pattern of the macros emerges, we may include it in the ptracer.h.

Indeed, that's the main idea.

But it's likely that there are some low-hanging fruit that we can already pick. For example, we could have a version of SETLINE that uses  `__LINE__` macro.

**Comment by singul4ri7y** [comment]
I know the repetitive macros do look gross in the example modules. But I would prefer not to keep something which wouldn't most likely be generalized for now. Let's keep things as simple as possible.
